### ISSUE TITLE
java.lang.NullPointerException in version 3.0

### ISSUE THREAD

**Issue by jeffpearce** [jenkinsci/github-autostatus-plugin#11]
In version 3.0 we are getting this NPE

java.lang.NullPointerException
	at org.jenkinsci.plugins.githubautostatus.GithubNotificationConfig.fromRun(GithubNotificationConfig.java:99)
	at org.jenkinsci.plugins.githubautostatus.GithubNotificationConfig.fromRun(GithubNotificationConfig.java:93)
	at org.jenkinsci.plugins.githubautostatus.GithubBuildStatusGraphListener.checkEnableBuildStatus(GithubBuildStatusGraphListener.java:244)
	at org.jenkinsci.plugins.githubautostatus.GithubBuildStatusGraphListener.onNewHead(GithubBuildStatusGraphListener.java:72)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.notifyListeners(CpsFlowExecution.java:1438)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$3.run(CpsThreadGroup.java:417)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.run(CpsVmExecutorService.java:35)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE

**Comment by sshepel** [comment]
Same issue for me, looks like global config object doesn't have `BuildStatusConfig.class`.

**Comment by jeffpearce** [comment]
@sshepel would it be possible to get a full stack trace to help me narrow it down?

**Comment by sshepel** [comment]
Provided in gitter DM.
