### ISSUE TITLE
no able to use this plugin.... not getting any status checks

### ISSUE THREAD

**Issue by screamingskulls** [jenkinsci/github-autostatus-plugin#98]
What am i missing ? 
currently using username and password as creds to github.

Error message: 
null
java.net.SocketTimeoutException: connect timed out
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:285)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
	at org.kohsuke.github.Requester._fetchOrRetry(Requester.java:523)
Caused: org.kohsuke.github.HttpException: Server returned HTTP response code: -1, message: 'null' for URL: https://github.hpe.com/api/v3/users/cloud
	at org.kohsuke.github.Requester._fetchOrRetry(Requester.java:537)
	at org.kohsuke.github.Requester._fetchOrRetry(Requester.java:542)
	at org.kohsuke.github.Requester._fetchOrRetry(Requester.java:542)
	at org.kohsuke.github.Requester._fetch(Requester.java:504)
	at org.kohsuke.github.Requester._fetch(Requester.java:496)
	at org.kohsuke.github.Requester.fetch(Requester.java:412)
	at org.kohsuke.github.GitHub.getUser(GitHub.java:567)
	at org.jenkinsci.plugins.githubautostatus.config.GithubNotificationConfig.extractGHRepositoryInfo(GithubNotificationConfig.java:257)
	at org.jenkinsci.plugins.githubautostatus.config.GithubNotificationConfig.fromRun(GithubNotificationConfig.java:146)
	at org.jenkinsci.plugins.githubautostatus.config.GithubNotificationConfig.fromRun(GithubNotificationConfig.java:124)
	at org.jenkinsci.plugins.githubautostatus.BuildStatusAction.connectNotifiers(BuildStatusAction.java:132)
	at org.jenkinsci.plugins.githubautostatus.BuildStatusAction.<init>(BuildStatusAction.java:115)
	at org.jenkinsci.plugins.githubautostatus.BuildStatusAction.newAction(BuildStatusAction.java:101)
	at org.jenkinsci.plugins.githubautostatus.GithubBuildStatusGraphListener.checkEnableBuildStatus(GithubBuildStatusGraphListener.java:274)
	at org.jenkinsci.plugins.githubautostatus.GithubBuildStatusGraphListener.onNewHead(GithubBuildStatusGraphListener.java:70)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.notifyListeners(CpsFlowExecution.java:1463)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$3.run(CpsThreadGroup.java:488)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.run(CpsVmExecutorService.java:38)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by MaheshGooner** [comment]
Having the same issue. anyworkarounds/suggestions to get this work ?
